name: Generate a build and push to another branch

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Permissions
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.repos.setBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'build',
              enforce_admins: true,
              required_status_checks: null,
              restrictions: null,
              required_pull_request_reviews: {
                dismissal_restrictions: {
                  users: [],
                  teams: []
                },
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1
              },
              allow_deletions: true,
              allow_force_pushes: true
            })

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build 
          FOLDER: frontend/dist 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}"
